config.py

#14 
- Changes for incorporating socket based connection for production env.

#14 Changes for socket based database connection

---

api/helpers/db_helper.py
api/models/ivr_prompt_response.py
api/models/user_program.py
api/services/prompt_service.py
api/services/registration_service.py
main.py

- Handled day one prompts.
- Updated user and registration details based on prompt response.

#29 Dost test daily workflow

---

README.md
api/services/registration_service.py
requirements-dev.txt

#17
- Added installation guideline in readme.

Readme updates

---

api/models/ivr_prompt.py
api/models/ivr_prompt_response.py
api/services/prompt_service.py
api/services/registration_service.py
main.py

- Fixes related to prompt details.
- Added Keypress to ivr prompt response table.

Fix IVR prompt response

---

api/models/user_module_content.py
api/models/user_program.py
api/services/__init__.py
api/services/call_log_service.py
api/services/content_service.py
api/services/prompt_service.py
api/services/registration_service.py
main.py

#44 Pilot testing flow feedbacks

---

api/models/user_program.py
api/services/prompt_service.py

- Fixed issue related to user program mapping.

Fix for user program mapping issue

---

.pre-commit-config.yaml
README.md
api/services/call_log_service.py
api/services/content_service.py
main.py
requirements-dev.txt

#50
- Installed pre-commit hook.
- Ran it for a few file for testing.

#50 Pre commit hook

---

api/services/registration_service.py

- Added check for existing user registration based on user phone number. This will avoid creating a new user if flow runs multiple time.

#59 Fix: Multiple registration entries issue

---

api/services/prompt_service.py

1. Capture complete prompt response instead of just response value
2. Removed unused code

Changes the way we were capturing prompt response

---

api/helpers/common_helper.py
api/models/call_log.py
api/services/call_log_service.py

#68
For capturing better system health and metrics, we needed to capture
1. Flow category
2. Call category
This PR contains those changes with which we can capture these set of data.
**Changes included are:**
- Added new columns to capture the call and flow categories
- Added new columns to capture the parent flow details
Here is the link to the document with updated notes.
https://docs.google.com/document/d/1b-Og8zZgMng91u1P_ZpRnmCQu_0J86tjYEdGP-cmC0o/edit#heading=h.jtsyjycnfiou

#68 handling different flow categories

---

api/models/call_log.py
api/services/call_log_service.py

#77
There were some lag in capturing data in our database once webhook triggers. So we can't rely in our database created on time for analytics. So in that case, we need to capture created on time from RP flow fun itself.
This PR has changes related to above.

#77 capture flow run "created on" time for RP flow run

---

api/helpers/db_helper.py
api/models/__init__.py
api/models/user_group.py
api/services/__init__.py
api/services/call_log_service.py
api/services/prompt_service.py
api/services/registration_service.py
api/services/user_group_service.py
main.py

#70 Changes to monitor user group switching

---

api/models/call_log.py
api/models/content.py
api/services/call_log_service.py

#82 call lag enhancements

---

api/helpers/db_helper.py
api/models/__init__.py
api/models/user_custom_fields.py
api/services/__init__.py
api/services/user_contact_service.py
main.py

#71 changes to monitor custom contact info

---

api/services/prompt_service.py

#76
Set preferred timeslot to default if user chooses other options.

#76 Added preferred time slot to afternoon as default if coming none

---

api/helpers/db_helper.py
api/models/__init__.py
api/models/ivr_prompt_mapping.py
api/models/user_program.py
api/services/prompt_service.py

#69
- This PR will help to capture/populate other table's column based on ivr prompts.

#69 Changes for prompt used in filling other tables

---

.github/ISSUE_TEMPLATE/bug_report.md

- Due to changes in labels, the auto-assignment of labels got impacted. This PR includes the fixes for the BUG issue template

Bug Issue template updates

---

.github/ISSUE_TEMPLATE/feature_request.md

- Due to changes in labels, the auto-assignment of labels got impacted. This PR includes the fixes for the feature issue template

Feature Issue template updates

---

api/models/registration.py
api/models/user.py

We initially added it for the user program table to capture the time slot. Now we can extend this for other tables like user, registration, etc.

Support for populating user and registration table based on user input

---

api/models/user_program.py
api/services/prompt_service.py
api/services/registration_service.py

#89 #97 User experience updates

---

api/models/registration.py

There are different formats for a user's phone number while registering new users. We fixed it in Call back while user creates a missed call, but a change is needed here as well.

Fix for multiple registration entry for one phone number

---

config.py

#15 
This is more of a fixing issue related to loading env variables from the system.

Fix the database URI in config

---

api/models/user_program.py
api/services/prompt_service.py

#126 Default user program fixes

---

api/helpers/db_helper.py
api/services/prompt_service.py
main.py

#131 
- The system starts getting some invalid responses from the user while responding to IVR prompts. In this PR, we handled the database exceptions due to these invalid responses.
- For every invalid response, we are filling it with `-2`.

[Hotfix] #131 invalid input syntax for IVR prompt response

---

api/models/__init__.py
api/models/webhook_transaction_log.py
api/services/__init__.py
api/services/transaction_log_service.py
main.py

#91 
- We need to store the webhook response in database, so that we can backfill the data if the response is not processed successfully.
- Created a new model for webhook_transaction_log
- Storing the jsonData to database table
- Marking the transaction log as processed after the jsonData is processed successfully.

#91 capture webhook call as log

---

api/services/registration_service.py

#143 
While updating the registration data the status is marked as `complete`. This is fixed now and we have added a check for updating the status on the basis of the previous registration status and any selection the user has done.

#143 Discrepencies in user signup status 

---

api/services/call_log_service.py
api/services/content_service.py

#127 
The `user_module_content_id` is not being populated in the `call_logs` table.

#127 User module content id is not populating in call logs

---

api/services/prompt_service.py
api/services/registration_service.py

#143 #148 
- As we will now be using a simple name (<response>) instead of a formatted name (<prompt name>_<response>) for IVR response. So made some changes to fetch this new response
- Fix the issue related to incorrect update of program id on updating the registration data

[hotfix] Correct the program updation and naming convention for ivr response

---

api/models/user_group.py
api/services/prompt_service.py
api/services/user_contact_service.py

#145 
The user_group is not marked as inactive. Made changes to update the status of user_group.

145 User group status not getting updated

---

main.py

#168 
We will be using some non-calling flows through which we can add or remove users from group or can update the custom fields.
So we need to handle these flows in our code base and also update the group and the custom fields for the users.

Handling webhooks for non-calling(dry_flow) flow

---

api/helpers/prompt_helper.py
api/models/user_program.py
api/services/prompt_service.py

#177 
The program id is set to default when a not signup flow runs.

[Hotfix] 177 program id not matching

---

api/services/call_log_service.py
api/services/content_service.py
api/services/prompt_service.py
api/services/registration_service.py
main.py

#[ISSUE_ID]
- Added check to update signup date only when the registration status is complete
- Replaced Index Error Exception handling with Exception, this way in all the error cases we will get the exception message

[HOTFIX] 177 signup date filled for users whose registration status is not complete

---

api/services/registration_service.py

#177
While updating a registration, the program id and status are not getting updated correctly.

[Hotfix] #177 Fix registration status and program assignment

---

api/services/registration_service.py

#181 
- Added checks to not update the status or program id to default if there is already a program id  and status and the user has not opted anything.

[HOTFIX] #181 Fix issue related to program id and status updating to default if user donot press anything on second call

---

api/services/registration_service.py

Syncing develop and main branch

Sync Main and Develop

---

api/models/user_custom_fields.py
api/models/user_group.py
api/services/user_contact_service.py
main.py

#209 
- Only updating the status to active of custom fields and user groups that are inactive and skipping the already active ones

#209 Optimise code for database queries

---

api/models/user_custom_fields.py

#209 
- Fix the function argument positioning

Change Function Argument Position

---

api/models/__init__.py
api/models/call_log.py
api/models/program_sequence.py
api/services/call_log_service.py
api/services/content_service.py
api/services/prompt_service.py
main.py

#224 
- Update program sequence whenever a call log is created.

#224 Added functionality to update program_sequence

---

api/services/content_service.py

#224 
- Getting program id using program_module instead of user_program

#224 Minor fix in fetching the program id 

---

.github/workflows/build.yml
README.md

#250
This PR includes the changes to implement CD (automatic deployment) to the staging server.

[#250] CD for staging server

---

.github/workflows/build.yml
config.py
main.py

#265 #269 
- Updated the config for the way we are going to use VPC serverless connector for connecting to database now.

#269  Serverless VPC connector based database connection

---

api/models/registration.py

https://github.com/DostEducation/RP_IVR_analytics/issues/255
- Added a column with name `number_of_eligible_kids `

Added new column in registration table

---

api/helpers/prompt_helper.py
api/services/prompt_service.py

(https://github.com/DostEducation/RP_IVR_callback/issues/42)
Stored the `has_smartphone` data as boolean

changed string to boolean

---

api/models/__init__.py
api/models/content_version.py
api/services/call_log_service.py

#295 
Adding logic to to fill content version in the call log table

adding content version in call_log

---

api/helpers/common_helper.py
api/models/user_program.py
api/services/user_program_service.py
main.py

Added logic to fill start_date and end_date in user program

start_date and end_date in user program

---

api/services/call_log_service.py

#309 
Get Hindi content version in case content version is not found for a language

Content version in ivr prompt response

---

api/models/user_program.py
api/services/registration_service.py

#325 
**Describe your changes in detail**
Added a condition while updating the user_program for an existing user.
Only the selected_user_program will update the program_id in the user_program table for an existing user.
Changes are required because when the existing users are getting multiple onboarding calls by making missed calls and in one of them, they select a program, and in the other, if they don't select any program and disconnect the call. Then the system is updating the user_program to the default program in the database.
Now, after these changes, if the user has an active user_program and the user gets an onboarding call and disconnects the call without selecting any user_program. Then the user_program does not update …

Added a check on user program updation logic.

---

api/models/contact_fields_mapping.py
api/services/contact_fields_mapping_service.py
api/services/user_program_service.py
main.py

Logic to update user data using custom fields and groups.
#268 
**Describe your changes in detail.**
Changes in the logic to compare the custom field getting in payload with the ContactFieldsMapping table field names.
Now retrieving all the field_name from the table and storing the result in a variable field_names.
Applied loop for all the field name in the table ContactFieldsMapping.
Using it to comparing the field getting in payload data.
These changes are required to decrease the execution time of the code in `dry_flow`.

logic to update user data from custom fields and groups

---

main.py

#337 
By generating logs in a cloud function, we can get detailed information about the execution of the cloud function, which can be used to diagnose and resolve issues that arise during the execution.
Here we are implementing the following level of logs in the system.
- INFO
- WARN
- ERROR

Generating logs in cloud function

---

main.py

#337 
Updating the default logging level to DEBUG for generating logs in cloud function as per log level and severity.
Here we are implementing the following level of logs in the system.
- INFO
- WARN
- ERROR

Generating logs in cloud function as per log level

---

api/services/__init__.py
api/services/program_sequence_service.py
main.py

#323 
Why these change required? What problem does it solve?
- Added program sequence service to get program sequence id for a user

Added program sequence service to get program sequence id for a user

---

main.py
utils/__init__.py
utils/loggingutils.py

#337 
Added loggingutils file to configure the logging based on the environment. 
- If the environment is "production", it uses the default handler from Google Cloud Logging to handle logs. 
- Otherwise, it uses the basic logging configuration from Python's built-in logging module.

Generating different level of logs in the cloud function.

---

api/services/prompt_service.py

#[ISSUE_ID]
Error severity log `IVR prompt response not found for call log id ____` is not required in the system. And raising for every call log. Due to this, we are getting webhook failure alerts in RP_IVR prod. Need to fix this.

Removed non required error log from the system.

---

.github/workflows/build.yml

#334 
**Describe your changes in detail**
In the code changes,
- The workflow is triggered for both `develop` and `main` branches now.
- There are two jobs - `deploy-staging` and `deploy-production`.
- The deploy-staging job deploys to the staging environment, while deploy-production deploys to the production environment only if the push was made to the main branch.
- Environment variables are split into two sets, one for staging and one for production, and they are appropriately named and assigned values specific to each environment.
- Added vpc-connecter to the `deploy-production` job in the workflow.

Implemented Continuous Deployment in the production.

---

api/services/prompt_service.py

#362 
**Describe your changes in detail**
- The system is generating some error logs for the responses which are not an integer keypress while responding to IVR prompts.
- Handled those exceptions occurring due to these invalid responses.

Handle the keypress if the keypress is not an integer

---

.github/workflows/build.yml
api/services/prompt_service.py

Release 17 March

---

api/services/prompt_service.py

Release 25 March

---

api/services/prompt_service.py
main.py

Release 20 April 2023

---

api/services/prompt_service.py
api/services/user_program_service.py
main.py

**Release Includes**
- https://github.com/DostEducation/RP_IVR_analytics/pull/377

Release 28th April 2023

---

.github/workflows/build.yml

#415 Integrate stabilize the database migration in RP_IVR

---

config.py

Corrected SQL URL connection for GitHub Action and database connection

---

.github/workflows/build.yml
config.py

The release includes changes:
- #413

Release 20 Oct 2023 v2

---

api/helpers/db_helper.py
api/services/prompt_service.py
config.py
main.py
manage.py

#461 
After the upgrade of packages, there were some issues related to these upgrades. So fixing these issues.

Fixed all the issues related to package upgrade
